mod abcdefghijklmnopqrstuvwxyz;
mod ascii_art_the_drunken_bishop_algorithm;
pub mod crop_circles;
mod encrypt_decrypt_of_enigma_machine;
mod equivalent_resistance_circuit_building;
mod ghost_legs;
mod logic_gates;
mod one_D_spreadsheet;
mod retro_typewriter_art;
pub mod six_degrees_of_kevin_bacon;
mod summer_challenge_2024;
mod the_travelling_salesman_problem;
mod what_the_brainfuck;
